# Creating NumPy Arrays from Python Lists

## 1. Importing NumPy

In [1]:
import numpy as np

## 2. Creating NumPy Arrays from Lists

In [2]:
# Python list
numbers = [1, 2, 3, 4, 5]

# Convert to NumPy array
arr = np.array(numbers)

print(arr)

[1 2 3 4 5]


In [3]:
# 2D array from nested list
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


## 3. Inspecting Array Properties

In [4]:
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

Shape: (5,)
Data Type: int64
Dimensions: 1


## 4. Basic Operations on Arrays

In [5]:
# Element-wise operations
print(arr + 2)
print(arr * 2)

[3 4 5 6 7]
[ 2  4  6  8 10]


In [6]:
# Python list behavior
numbers = [1, 2, 3]

print(numbers * 2)   # duplicates list

[1, 2, 3, 1, 2, 3]


In [7]:
# NumPy array behavior
arr = np.array([1, 2, 3])

print(arr * 2)  # multiplies elements

[2 4 6]


## Conclusion

NumPy arrays are more efficient and suitable for numerical operations compared to Python lists. Arrays support element-wise operations and provide useful properties like shape, data type, and dimensions. This makes them essential for data science and machine learning tasks.