# Creating NumPy Arrays from Python Lists

## 1. Importing NumPy

In [1]:
import numpy as np

## 2. Creating NumPy Arrays from Lists

In [2]:
# Python list
numbers = [1, 2, 3, 4, 5]

# Convert to NumPy array
arr = np.array(numbers)

print(arr)

[1 2 3 4 5]


In [3]:
# 2D array from nested list
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


## 3. Inspecting Array Properties

In [4]:
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

Shape: (5,)
Data Type: int64
Dimensions: 1


## 4. Basic Operations on Arrays

In [5]:
# Element-wise operations
print(arr + 2)
print(arr * 2)

[3 4 5 6 7]
[ 2  4  6  8 10]


In [6]:
# Python list behavior
numbers = [1, 2, 3]

print(numbers * 2)   # duplicates list

[1, 2, 3, 1, 2, 3]


In [7]:
# NumPy array behavior
arr = np.array([1, 2, 3])

print(arr * 2)  # multiplies elements

[2 4 6]


## Conclusion

NumPy arrays are more efficient and suitable for numerical operations compared to Python lists. Arrays support element-wise operations and provide useful properties like shape, data type, and dimensions. This makes them essential for data science and machine learning tasks.

# Basic Mathematical Operations on NumPy Arrays

This section demonstrates:
- Element-wise arithmetic operations
- Scalar operations
- Comparison with Python lists
- Common mistakes and how to avoid them

## 1. Element-Wise Array Operations

Add, subtract, multiply, and divide arrays of the same shape. Operations are applied to corresponding elements.

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

## 2. Scalar Operations on Arrays

Apply a single value (scalar) to all elements of an array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("arr + 10:", arr + 10)
print("arr * 3:", arr * 3)
print("arr / 2:", arr / 2)

## 3. Comparing NumPy Arrays and Python Lists

See how math operations differ between lists and arrays.

In [ ]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print("Python list * 2:", py_list * 2)  # List is duplicated
print("NumPy array * 2:", np_array * 2)  # Elements are multiplied

## 4. Avoiding Common Mistakes

Examples of shape mismatch and type issues.

In [ ]:
# Shape mismatch
try:
    a = np.array([1, 2, 3])
    b = np.array([1, 2])
    print(a + b)
except ValueError as e:
    print("Shape mismatch error:", e)

# Type issue
try:
    arr = np.array([1, 2, 'three'])
    print(arr + 1)
except Exception as e:
    print("Type error:", e)