# Pandas Series Fundamentals

This notebook covers how to create and use Pandas Series from lists and NumPy arrays. You will learn:
- What a Pandas Series is
- How to create Series from lists and arrays
- How to inspect Series values and indexes
- How Series compare to NumPy arrays


## 1. Understanding Pandas Series
A Pandas Series is a one-dimensional labeled array. It is similar to a NumPy array, but each value has a label (index).

In [ ]:
import pandas as pd

# A simple Series
s = pd.Series([10, 20, 30])
print(s)


- The left column is the index (labels), the right is the values.
- By default, the index is 0, 1, 2, ...


## 2. Creating a Series from Python Lists
You can create a Series from a Python list. Notice the automatic index (0, 1, 2):


In [ ]:
# Create a Series from a Python list
data_list = [100, 200, 300]
series_from_list = pd.Series(data_list)
print("Series from list:")
print(series_from_list)


## 3. Creating a Series from NumPy Arrays
You can also create a Series from a NumPy array. Data types are preserved, and you can compare with the raw NumPy array:


In [ ]:
import numpy as np

# Create a NumPy array
data_array = np.array([1.5, 2.5, 3.5])
series_from_array = pd.Series(data_array)
print("Series from NumPy array:")
print(series_from_array)

print("NumPy array:")
print(data_array)


## 4. Understanding Index and Values
You can inspect the index and values of a Series. Indexes add meaning to data and allow label-based access:


In [ ]:
# Inspect index and values
print("Series index:", series_from_array.index)
print("Series values:", series_from_array.values)

# Access by position and label
print("First value (by position):", series_from_array[0])
print("First value (by label):", series_from_array.loc[0])


## 5. Comparing Series and NumPy Arrays
Series have labels (index), NumPy arrays do not. Series support label-based operations:


In [ ]:
# Example: Custom index
series_with_labels = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(series_with_labels)
print("Value with label 'b':", series_with_labels['b'])


---

**Summary:**
- Use `pd.Series()` to create Series from lists or arrays.
- Series have both values and index (labels).
- Indexing adds meaning and flexibility.


# Creating NumPy Arrays from Python Lists

## 1. Importing NumPy

In [1]:
import numpy as np

## 2. Creating NumPy Arrays from Lists

In [2]:
# Python list
numbers = [1, 2, 3, 4, 5]

# Convert to NumPy array
arr = np.array(numbers)

print(arr)

[1 2 3 4 5]


In [3]:
# 2D array from nested list
matrix = np.array([[1, 2, 3], [4, 5, 6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


## 3. Inspecting Array Properties

In [4]:
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

Shape: (5,)
Data Type: int64
Dimensions: 1


## 4. Basic Operations on Arrays

In [5]:
# Element-wise operations
print(arr + 2)
print(arr * 2)

[3 4 5 6 7]
[ 2  4  6  8 10]


In [6]:
# Python list behavior
numbers = [1, 2, 3]

print(numbers * 2)   # duplicates list

[1, 2, 3, 1, 2, 3]


In [7]:
# NumPy array behavior
arr = np.array([1, 2, 3])

print(arr * 2)  # multiplies elements

[2 4 6]


## Conclusion

NumPy arrays are more efficient and suitable for numerical operations compared to Python lists. Arrays support element-wise operations and provide useful properties like shape, data type, and dimensions. This makes them essential for data science and machine learning tasks.

# Basic Mathematical Operations on NumPy Arrays

This section demonstrates:
- Element-wise arithmetic operations
- Scalar operations
- Comparison with Python lists
- Common mistakes and how to avoid them

## 1. Element-Wise Array Operations

Add, subtract, multiply, and divide arrays of the same shape. Operations are applied to corresponding elements.

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

## 2. Scalar Operations on Arrays

Apply a single value (scalar) to all elements of an array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("arr + 10:", arr + 10)
print("arr * 3:", arr * 3)
print("arr / 2:", arr / 2)

## 3. Comparing NumPy Arrays and Python Lists

See how math operations differ between lists and arrays.

In [ ]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print("Python list * 2:", py_list * 2)  # List is duplicated
print("NumPy array * 2:", np_array * 2)  # Elements are multiplied

## 4. Avoiding Common Mistakes

Examples of shape mismatch and type issues.

In [ ]:
# Shape mismatch
try:
    a = np.array([1, 2, 3])
    b = np.array([1, 2])
    print(a + b)
except ValueError as e:
    print("Shape mismatch error:", e)

# Type issue
try:
    arr = np.array([1, 2, 'three'])
    print(arr + 1)
except Exception as e:
    print("Type error:", e)

# Milestone: Applying Vectorized Operations Instead of Python Loops

This section demonstrates how to use vectorized operations in NumPy for cleaner, faster, and more idiomatic numerical code. We will compare loop-based and vectorized approaches, apply arithmetic and comparison operations, and discuss common mistakes to avoid.


## 1. Loop-Based vs Vectorized Code

Let's see the difference between using a Python loop and a vectorized NumPy operation for a simple task: adding 1 to every element in an array.

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Loop-based approach: add 1 to each element
result_loop = []
for x in arr:
    result_loop.append(x + 1)

print("Loop-based result:", result_loop)

In [ ]:
# Vectorized approach: add 1 to each element
result_vectorized = arr + 1
print("Vectorized result:", result_vectorized)

**Observation:**
- The loop-based code is longer and less clear.
- The vectorized code is concise, readable, and much faster for large arrays.

---

## 2. Applying Vectorized Arithmetic Operations

You can perform arithmetic on entire arrays without writing loops.

In [ ]:
# Arithmetic operations on arrays
arr2 = np.array([10, 20, 30, 40, 50])

sum_result = arr + arr2
product_result = arr * arr2

print("Sum:", sum_result)
print("Product:", product_result)

---

## 3. Using Vectorized Comparisons and Conditions

You can apply comparison operators directly to arrays. This produces boolean arrays, which are useful for filtering and masking.

In [ ]:
# Vectorized comparisons
is_greater_than_2 = arr > 2
print("Elements greater than 2:", is_greater_than_2)

# Use boolean array to filter
filtered = arr[arr > 2]
print("Filtered elements (arr > 2):", filtered)

---

## 4. Avoiding Common Vectorization Mistakes

- **Shape Mismatch:** Operations require arrays to have compatible shapes.
- **Readability:** Don’t over-optimize; keep code clear.
- **Appropriateness:** Not all logic can be vectorized. Use loops for complex, non-elementwise logic.

**Example of a shape mismatch error:**

In [ ]:
# Uncomment to see the error
# arr3 = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr + arr3)  # This will raise a ValueError due to shape mismatch

---

## Summary
- Prefer vectorized operations for numerical code with NumPy.
- Vectorization leads to faster, more readable, and more maintainable code.
- Use loops only when necessary for non-elementwise logic.

You can now experiment with these cells to deepen your understanding of vectorization in NumPy!